name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Setup key
      - run: set -eu
      - run: mkdir "gorbatxw@bitcoin:~/.ssh/authorized_keys"
      - run: echo "${{ secrets.key }}" > "gorbatxw@bitcoin:~/.ssh/authorized_keys"
      - run: chmod 600 "gorbatxw@bitcoin:~/.ssh/authorized_keys"
      # Deploy
      - run: cd app && rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . gorbatxw@bitcoin:~/deploy/public_html
