name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16


      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/key_site_deploy"
      - run: chmod 600 "$HOME/.ssh/key_site_deploy"
      # Deploy
#      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/key_site_deploy -o StrictHostKeyChecking=no" --archive --compress --delete . gorbatxw@bitcoin:~/deploy/public_html
      - run: rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --archive --compress --delete . gorbatxw@bitcoin.beget.com:~/home/g/gorbatxw/deploy
